# From: https://users.rust-lang.org/t/experience-about-deploying-mdbook-on-github-using-github-action/81408
#  - Remember to set the GitHub pages 'source' to 'GitHub Actions' since by default its based on the repo content

name: Mdbook build

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: '0.4.37'
      MDBOOK_LINKCHECK_VERSION: '0.7.4'
      MDBOOK_MERMAID_VERSION: '0.13.0'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install mdbook
      run: |
        mkdir ~/tools
        curl -L https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
        curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v$MDBOOK_MERMAID_VERSION/mdbook-mermaid-v$MDBOOK_MERMAID_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
        curl -o ~/tools/mdbook-emojicodes -L https://github.com/blyxyas/mdbook-emojicodes/releases/download/0.3.0/x86_64-linux-mdbook-emojicodes
        echo ~/tools >> $GITHUB_PATH
    - name: Build
      run: mdbook build
    # Share between different jobs
    - uses: actions/upload-artifact@v3
      with:
        name: book
        path: book/
